title: Mount components in card or plastic
hero_image: images/banner.png
description: Mount components in card or plastic
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - 
    title: Mount components in card or plastic
