title: Monter les composants sur du carton ou du plastique
hero_image: images/banner.png
description: Monter les composants sur du carton ou du plastique
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - 
    title: Monter les composants sur du carton ou du plastique
